#! /usr/bin/env php

<?php
use WeiFang\PlayCommand;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('a card game of texas hold’em poker', '1.0');

$app->add(new PlayCommand);

$app->run();